name: Run Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # 毎日 UTC 18:00 = JST 3:00

permissions:
  contents: read
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/316012052764/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'toggl-drive-uploader@toggl-to-drive-automation.iam.gserviceaccount.com'
          token_format: 'access_token'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests google-api-python-client google-auth google-auth-oauthlib

      - name: Run script
        env:
          GOOGLE_DRIVE_TOKEN: ${{ secrets.GOOGLE_DRIVE_TOKEN }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          TOGGL_API_TOKEN: ${{ secrets.TOGGL_API_TOKEN }}
          TOGGL_WORKSPACE_ID: ${{ secrets.TOGGL_WORKSPACE_ID }}
        run: python main.py
